version: '3.8'

services:

  nest-back:
    build: .
    volumes:
      - .:/nest-back
    container_name: nest-back
    hostname: nest-back
    depends_on:
      - nest-db
    ports:
      - '3030:3030'
    expose:
      - '3030'
    restart: unless-stopped
    env_file: ./.env
    networks:
      - nestx

  nest-db:
    image: postgres:15.2-alpine3.17
    container_name: nest-db
    hostname: nest-db
    env_file: .db.env
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    expose:
      - '5432'
    ports:
      - '5432:5432'
    restart: always
    networks:
      - nestx

  nest-pgadmin:
    container_name: nest-pgadmin
    hostname: nest-pgadmin
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      - nest-db
    image: dpage/pgadmin4
    env_file: .pgadmin.env
    expose:
      - '80'
    ports:
      - '5051:80'
    restart: always
    networks:
      - nestx
    logging:
      driver: none

networks:
  nestx:
    external: true

